services:
  app:
    build: .
    command: /app/scripts/start-main.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://postgres:admin@postgres:5432/qr_payment_db
      - ADMIN_DB_URL=postgresql://postgres:admin@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./app/infrastructure/db/postgres/migrations/versions:/app/app/infrastructure/db/postgres/migrations/versions  
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 3
    #   start_period: 5s
    restart: unless-stopped
    networks:
      - qrb-network

  payment-poller:
    build:
      context: .
    command: /app/scripts/start-poller.sh
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://postgres:admin@postgres:5432/qr_payment_db
      - ADMIN_DB_URL=postgresql://postgres:admin@postgres:5432/postgres
    restart: unless-stopped
    networks:
      - qrb-network


  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=qr_payment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - qrb-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qr_payment_db"] # явное указание т.к. нет системного пользователя root
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - qrb-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  qrb-network:
    external: true

volumes:
  postgres_data:
  redis_data: