apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-script
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    
    echo "🔄 Creating database if not exists..."
    python /app/scripts/create_db.py
    
    echo "🔄 Running migrations..."
    python /app/scripts/migrate.py
    
    echo "✅ Database initialization completed!"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
spec:
  template:
    spec:
      containers:
      - name: init-db
        image: pet-qrb-back:latest
        imagePullPolicy: Never
        command: ["/bin/bash", "/scripts/init-db.sh"]
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: pet-qrb-back-config
              key: DB_URL
        - name: ADMIN_DB_URL
          valueFrom:
            configMapKeyRef:
              name: pet-qrb-back-config
              key: ADMIN_DB_URL
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: pet-qrb-back-config
              key: DB_NAME
        volumeMounts:
        - name: init-script
          mountPath: /scripts
      volumes:
      - name: init-script
        configMap:
          name: init-db-script
          defaultMode: 0755
      restartPolicy: OnFailure